spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
  config:
    import:
      - optional:file:.env[.properties]
      - aws-parameterstore:/chaing/
    activate:
      on-profile: test

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  batch:
    jdbc:
      initialize-schema: always
      platform: mysql
    job:
      enabled: false

application:
  security:
    jwt:
      secret-key: aEVSS1kwanBWVUVSMTVUeVVQbFdsTVFpd2x1UG9lY1I=
      access-token-expiration: 86400000
      refresh-token-expiration: 86400000
